# Generated by Django 2.2.5 on 2019-09-14 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactmodel',
            name='slug',
        ),
    ]
