# Generated by Django 2.2.5 on 2019-09-14 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_remove_contactmodel_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmodel',
            name='How_we_are',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contactmodel',
            name='PHone_number',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='contactmodel',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
