# Generated by Django 2.2.5 on 2019-09-14 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_auto_20190914_0046'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmodel',
            name='status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=0),
        ),
    ]
