# Generated by Django 2.2.5 on 2019-09-14 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_contactmodel_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmodel',
            name='slug',
            field=models.SlugField(max_length=200, null=True, unique=True),
        ),
    ]
