# Generated by Django 2.2.5 on 2019-09-14 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0005_contactmodel_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactmodel',
            options={'ordering': ['-created_on'], 'verbose_name_plural': 'Customer Contact'},
        ),
        migrations.RenameField(
            model_name='contactmodel',
            old_name='How_we_are',
            new_name='adress',
        ),
    ]
