# Generated by Django 2.2.5 on 2019-09-14 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('About', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutmodel',
            name='objective_aim',
            field=models.TextField(blank=True, null=True),
        ),
    ]
