# Generated by Django 2.2.5 on 2019-09-17 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ourteam', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='membersmodel',
            options={'ordering': ['-title'], 'verbose_name_plural': 'Members'},
        ),
    ]
