# Generated by Django 2.2.5 on 2019-09-17 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ourteam', '0002_auto_20190917_0046'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='membersmodel',
            options={'ordering': ['-created_on'], 'verbose_name_plural': 'Members'},
        ),
    ]
